### ISSUE TITLE
[SATURN CONTROLLER]  No coin/select button

### ISSUE THREAD

**Issue by M-Walrus** [MiSTer-LLAPI/NeoGeo_MiSTer#3]
There is currently no coin/select button for this core, making another controller plugged in being necessary for proper operation, when using a saturn controller. I recommend using the top right bumper button for this, as the front buttons should be reserved for the user to select a four button layout that spans horizontally like on the original neo geo system, by using the button rebinding feature, if they so desire.

Previously you could insert a coin by holding down start, since it had that weird quirk where it would "ghost" the select button when held down. this worked well for the neo-geo core (w/ saturn controller) in my previous testing, but does not seem to work the same way anymore.

**Comment by MP2E** [comment]
Fixed!
